### ISSUE TITLE
Bundle is re-ordering my CSS

### ISSUE THREAD

**Issue by hatzipanis** [bigcommerce/stencil-cli#282]
I have a pretty standard SCSS entry file with a bunch of `@import`'s. In development (`stencil start`) my SCSS is being compiled correctly. When I go to export my theme (`stencil bundle`) my SCSS is re-ordered in ways I wish it wouldn't. Specifically, it looks like like it is playing with the order of my `@mixin` or `@include`'s which is causing inheritance nightmares. 

Am I right in assuming this is `stencil bundle` doing this? Is there a way to make it behave more like `stencil start` with regards to SCSS compilation?

**Comment by mcampa** [comment]
`stencil bundle` does not compile any sass, it just validates and bundles all the required files to run in production. 

In production, the css compilation is ran in our servers by the same tools and same versions that are used by `stencil start` ([libsass](http://sass-lang.com/libsass))  and cached by the cdn. The only difference between running locally and production is that the css is minified and the source maps are not included.

Can you provide an example of anything that you see different from running locally and in a production store?

**Comment by hatzipanis** [comment]
Thanks so much for the quick response, it's appreciated. This is strange then.

I'll try be as specific as possible.

We're using Inuitcss which has a `utilities/_utilities.widths` import. You can see the contents of this file [here](https://github.com/inuitcss/inuitcss/blob/develop/utilities/_utilities.widths.scss). In that file on lines starting 134 there's an `@include` and then on lines starting 150 albeit slightly more complicated.

In the local order my CSS is compiled in the correct order:

```css
.u-1\/2 {
  width: 50% !important;
}

...

@media (min-width: 20em) {
  .u-1\/2\@mobile {
    width: 50% !important; 
  }
}

...


@media (min-width: 46.25em) {
  .u-1\/2\@tablet {
    width: 50% !important; 
  }
}
```

In production is compiled in a different order (and minified of course):

```css
.u-1\/2\@tablet{width:50%!important}

...

.u-1\/2{width:50%!important}

...

.u-1\/2\@mobile{width:50%!important}
```

Please let me know if you require anything else.
